import os
from playwright.sync_api import sync_playwright


# =====================================================================
# 1. METADATA EXTRACTION ENGINE
# =====================================================================
def extract_form_metadata(page) -> list:
    """
    Scans the active web page for interactive elements and maps
    their structures, types, labels, and option configurations.
    """
    # Target text fields, textareas, dropdowns, and checkboxes
    interactive_elements = page.locator(
        "input[type='text'], input[type='email'], input[type='checkbox'], input:not([type]), textarea, select")
    count = interactive_elements.count()

    form_fields = []

    for i in range(count):
        element = interactive_elements.nth(i)
        element_id = element.get_attribute("id")
        input_type = element.get_attribute("type")
        tag_name = element.evaluate("el => el.tagName.toLowerCase()")

        # Classify the interactive element type
        field_type = "checkbox" if input_type == "checkbox" else tag_name

        if element_id:
            # Match standard labels using the 'for' attribute
            label_element = page.locator(f"label[for='{element_id}']")

            if label_element.count() > 0:
                label_text = label_element.inner_text().strip()
            else:
                # Fallback: Check if the element is nested within a label wrapper
                nested_label = page.locator(f"label:has(input#{element_id})")
                if nested_label.count() > 0:
                    label_text = nested_label.inner_text().strip()
                else:
                    label_text = f"Unnamed field ({element_id})"

            field_data = {
                "id": element_id,
                "label": label_text,
                "type": field_type,
                "options": []
            }

            # Extract options specifically for dropdown selects
            if field_type == "select":
                options_locator = element.locator("option")
                for j in range(options_locator.count()):
                    opt_text = options_locator.nth(j).inner_text().strip()
                    if opt_text:
                        field_data["options"].append(opt_text)

            form_fields.append(field_data)

    return form_fields


# =====================================================================
# 2. USER INTERACTION ENGINE
# =====================================================================
def prompt_user_for_inputs(form_metadata: list) -> dict:
    """
    Iterates through the extracted form metadata and interacts with
    the terminal user to cleanly gather structured configuration data.
    """
    print("\n📋 Form Found! Please fill in the configuration details below:")
    print(form_metadata)

    user_responses = {}

    for field in form_metadata:
        if field["type"] == "checkbox":
            choice = input(f"\n👉 Do you want to check [{field['label']}]? (yes/no): ").strip().lower()
            should_check = choice in ['yes', 'y', 'true', '1']
            user_responses[field["id"]] = (should_check, "checkbox")

        elif field["type"] == "select":
            print(f"\n👉 Dropdown found for [{field['label']}]. Available options:")
            for idx, opt in enumerate(field["options"], 1):
                print(f"  [{idx}] {opt}")

            choice = input(f"Enter the exact text or option number for [{field['label']}]: ")
            if choice.isdigit() and 1 <= int(choice) <= len(field["options"]):
                user_responses[field["id"]] = (field["options"][int(choice) - 1], "select")
            else:
                user_responses[field["id"]] = (choice, "select")
        else:
            user_val = input(f"\n👉 Enter text for [{field['label']}]: ")
            user_responses[field["id"]] = (user_val, "text")

    return user_responses


# =====================================================================
# 3. FORM FILLING AUTOMATION ENGINE
# =====================================================================
# def fill_web_form(page, user_responses: dict):
#     """
#     Executes automation sequences inside the active web window
#     using the structured dictionary map generated by user inputs.
#     """
#     print("\n🚀 Injecting collected data back into the web form...")
#
#     for element_id, (value, field_type) in user_responses.items():
#         if field_type == "checkbox":
#             page.set_checked(f"#{element_id}", value)
#         elif field_type == "select":
#             page.select_option(f"#{element_id}", label=value)
#         else:
#             page.fill(f"#{element_id}", value)
#
#     print("✅ Form successfully updated!")


def fill_web_form(page, user_responses: dict):
    """
    Executes automation sequences inside the active web window
    using the structured dictionary map generated by user inputs.
    """
    print("\n🚀 Injecting collected data back into the web form...")

    for element_id, (value, field_type) in user_responses.items():
        selector = f"#{element_id}"

        if field_type == "checkbox":
            page.set_checked(selector, value)

        elif field_type == "select":
            print(f"  Selecting dropdown option '{value}' for {selector}...")
            try:
                # 1. First attempt: Try to match exactly by visible label text
                page.select_option(selector, label=value)
            except Exception:
                print(f"  ⚠️ Visible text '{value}' failed. Attempting alternative matching strategy...")
                try:
                    # 2. Second attempt: Fallback to matching by 'value' attribute or index string
                    page.select_option(selector, value=value)
                except Exception as e:
                    # 3. Third attempt: In case the options are slow to load dynamically,
                    # fetch all options directly from the element to find a partial match
                    options = page.locator(f"{selector} option").all_inner_texts()
                    cleaned_options = [o.strip() for o in options if o.strip()]

                    print(
                        f"  ❌ Selection failed completely. Available options in this dropdown were: {cleaned_options}")
                    print(f"  Skipping field {selector} due to mismatch error.")
        else:
            page.fill(selector, value)

    print("✅ Form update sequence finished!")


# =====================================================================
# SETUP & ORCHESTRATION PIPELINE
# =====================================================================
def create_test_html():
    html_content = """
    <!DOCTYPE html>
    <html>
    <head><title>Modular Form Test</title></head>
    <body>
        <form>
            <div><label for="fullName">Full Name</label><input type="text" id="fullName"></div>
            <div>
                <label for="preferredRole">Preferred Job Role</label>
                <select id="preferredRole">
                    <option value="dev">Software Engineer</option>
                    <option value="pm">Product Manager</option>
                </select>
            </div>
            <div><label for="terms"><input type="checkbox" id="terms"> Accept Terms</label></div>
        </form>
    </body>
    </html>
    """
    file_path = os.path.abspath("modular_test.html")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    return f"file://{file_path}"


def main():
    target_url = "file:///C:/Users/Hackathon_user/Code/playwright_extract_text/forms/form_4.html"

    # with sync_playwright() as p:
    # browser = p.chromium.launch(headless=False)

    # Start Playwright manually without the 'with' context manager
    playwright_instance = sync_playwright().start()

    browser = playwright_instance.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto(target_url)

    # Step 1: Extract form details
    print("🔍 Scanning page configuration...")
    form_metadata = extract_form_metadata(page)

    # Step 2: Prompt user for answers completely detached from Playwright runtime loop
    user_data = prompt_user_for_inputs(form_metadata)

    # Step 3: Fill the web form natively
    fill_web_form(page, user_data)
    # page.pause()  # <-- Add this line here

    # page.wait_for_timeout(4000)
    input("\n🏁 Form filled! Press [ENTER] in this terminal to close the browser...")
    # page.wait_for_timeout(9999999)  # Set a massive timeout delay
    browser.close()

if os.path.exists("modular_test.html"):
    os.remove("modular_test.html")


def main_connect_existing():
    with sync_playwright() as p:
        print("🔗 Connecting to the already running browser session on port 9222...")

        # Connect to your active browser instead of launching a new one
        browser = p.chromium.connect_over_cdp("http://localhost:9222")

        # Access the already active browser tab/page
        default_context = browser.contexts[0]
        page = default_context.pages[0]

        print(f"🎯 Connected! Current active tab title is: '{page.title()}'")

        # Step 1: Extract form details from the live page
        print("Scraping active page fields...")
        form_metadata = extract_form_metadata(page)

        if not form_metadata:
            print("⚠️ No fields detected on the current active tab. Are you on the form page?")
            return

        # Step 2: Prompt user for answers in the terminal
        user_data = prompt_user_for_inputs(form_metadata)

        # Step 3: Automatically fill the live web form
        fill_web_form(page, user_data)

        print("\n🏁 Automation complete! The browser will stay open because you are controlling it live.")
        # Notice we do NOT close the browser here, keeping your live session perfectly intact.



if __name__ == "__main__":
    # main()
    main_connect_existing()
